### ISSUE TITLE
The NoEnterPlayer Flag easy bypassable

### ISSUE THREAD

**Issue by andris155** [ShaneBeee/GriefPreventionFlags#138]
### Description

The NoEnterPlayer Flag easy bypassable.
When use the sprint and jump.

### Steps to Reproduce

https://www.youtube.com/watch?v=g8k_ACsfIdA

### Expected Behavior

The NoEnterPlayer Flag not bypassable. 

### Server Information
* **Server version/platform:** git-Yatopia-"011dd34" (MC: 1.16.4)       
* **GriefPrevention Version:** 16.16.0       
* **GriefPreventionFlags Version:** 5.9.4

**Comment by Tnology** [comment]
+1
This issue should be fixed.

**Comment by ShaneBeee** [comment]
I will look into trying to find a way to solve this.

As of right now, I can not replicate it. I have tried every method of sneaking, running, jump, etc to try get into a claim, but still can't. 

Im not saying its not possible, im just saying I can't replicate it. And when I can't replicate it, its hard to fix something since I won't be able to know whether or not a fix has actually worked.

**Comment by boehs** [comment]
Here is a alternate way to do this

https://youtu.be/hhqedjv4tgw
